# Generated by Django 4.0.6 on 2022-07-24 09:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=accounts.models._make_account_number, max_length=12)),
                ('owner', models.CharField(max_length=255)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
