# Generated by Django 4.0.6 on 2022-07-24 09:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(default=accounts.models._make_account_number, max_length=28),
        ),
    ]
