# Generated by Django 4.0.6 on 2022-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('number_debited', models.CharField(max_length=28)),
                ('number_credited', models.CharField(max_length=28)),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['number'], name='accounts_ac_number_92e5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['timestamp'], name='accounts_tr_timesta_5171d5_idx'),
        ),
    ]
